apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-todo-api
  labels:
    app: laravel-todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-todo-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: laravel-todo-api
    spec:
      containers:
      - name: laravel-todo-api
        image: laravel-todo-api:local
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: laravel-todo-api-config
              key: APP_NAME
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: laravel-todo-api-config
              key: APP_ENV
        - name: APP_DEBUG
          valueFrom:
            configMapKeyRef:
              name: laravel-todo-api-config
              key: APP_DEBUG
        - name: APP_URL
          valueFrom:
            configMapKeyRef:
              name: laravel-todo-api-config
              key: APP_URL
        - name: DB_CONNECTION
          value: "mysql"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: laravel-todo-api-secrets
              key: db-host
        - name: DB_PORT
          value: "3306"
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: laravel-todo-api-secrets
              key: db-name
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: laravel-todo-api-secrets
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: laravel-todo-api-secrets
              key: db-password
        - name: LOG_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: laravel-todo-api-config
              key: LOG_CHANNEL
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
