AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for RDS MySQL database for Laravel Todo API in ap-southeast-1'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID of the EKS cluster VPC

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The list of private subnet IDs for the DB subnet group

  DBName:
    Type: String
    Description: The database name
    Default: laravel_todo_api
    MinLength: 1
    MaxLength: 64
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9_]*'

  DBUsername:
    Type: String
    Description: The database admin username
    Default: admin
    MinLength: 1
    MaxLength: 16
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'

  DBPassword:
    Type: String
    Description: The database admin password
    NoEcho: true
    MinLength: 8
    MaxLength: 41
    AllowedPattern: '[a-zA-Z0-9]*'

  DBInstanceClass:
    Type: String
    Description: The database instance type
    Default: db.t3.micro
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium

Resources:
  # DB Subnet Group
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS database
      SubnetIds: !Ref SubnetIds

  # Security Group for RDS
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS database
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          Description: Allow MySQL access from EKS cluster
          CidrIp: 10.0.0.0/16  # This should match your VPC CIDR

  # RDS Instance
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: mysql
      EngineVersion: 8.0
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      StorageType: gp2
      MultiAZ: true
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
      Tags:
        - Key: Name
          Value: Laravel Todo API Database
        - Key: Environment
          Value: Production

Outputs:
  DBEndpoint:
    Description: The connection endpoint for the database
    Value: !GetAtt DBInstance.Endpoint.Address
  DBPort:
    Description: The port for the database
    Value: !GetAtt DBInstance.Endpoint.Port
