apiVersion: v1
kind: Secret
metadata:
  name: laravel-todo-api-secrets
  namespace: default
type: Opaque
data:
  # These values will be replaced during deployment
  db-host: ${DB_HOST_BASE64}
  db-name: ${DB_NAME_BASE64}
  db-username: ${DB_USERNAME_BASE64}
  db-password: ${DB_PASSWORD_BASE64}
