apiVersion: v1
kind: Secret
metadata:
  name: laravel-todo-api-secrets
  namespace: default
type: Opaque
data:
  db-host: bGFyYXZlbC10b2RvLWFwaS1yZHMtZGJpbnN0YW5jZS1taGJ0ZGFnb3p6aW0uY3NodHZ0d3Jqazd0LmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db-name: bGFyYXZlbF90b2RvX2FwaQ==
  db-username: YWRtaW4=
  db-password: UGFzc3dvcmQxMjM=
