apiVersion: v1
kind: Secret
metadata:
  name: laravel-todo-api-secrets
  namespace: default
type: Opaque
data:
  # Example values (base64 encoded)
  db-host: bGFyYXZlbC10b2RvLWFwaS1yZHMtZGJpbnN0YW5jZS5jc2h0dnR3cmprN3QuYXAtc291dGhlYXN0LTEucmRzLmFtYXpvbmF3cy5jb20=
  db-name: bGFyYXZlbF90b2RvX2FwaQ==
  db-username: YWRtaW4=
  db-password: UGFzc3dvcmQxMjM=
