apiVersion: v1
kind: Service
metadata:
  name: laravel-todo-api
  labels:
    app: laravel-todo-api
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: laravel-todo-api
  type: ClusterIP
